#!/usr/bin/env python3
"""Generate source/font.c: the app's 16x32 bitmap font, from JetBrains Mono.

    python3 art/make_font.py <JetBrainsMono[wght].ttf> [preview.png]

Font: JetBrains Mono (SIL Open Font License 1.1, no Reserved Font Name),
JetBrainsMono[wght].ttf from github.com/google/fonts/tree/main/ofl/jetbrainsmono.
The bitmap is a modified version of that font, so it stays under the OFL; the
license text ships in the pkg as USRDIR/OFL.txt (pkgfiles/USRDIR/OFL.txt).

Layout, as libfont3d's AddFontFromBitmapArray(font, tex, 32, 255, 16, 32, 2,
BIT0_FIRST_PIXEL) reads it: characters 32..255 (Latin-1), each 32 rows of 16
pixels, 2 bits per pixel (0 = clear .. 3 = full), 4 pixels per byte with the
first pixel in bits 0-1: 4 bytes per row, 128 bytes per character.
"""
import os, sys
from PIL import Image, ImageDraw, ImageFont

W, H, FIRST, LAST = 16, 32, 32, 255
SIZE, WEIGHT, BASELINE = 24, 650, 24        # 24 px: 14.4 px advance, ascent 23 + descent 7 fit the cell

def render(ttf):
    f = ImageFont.truetype(ttf, SIZE)
    f.set_variation_by_axes([WEIGHT])
    glyphs = []
    for c in range(FIRST, LAST + 1):
        img = Image.new('L', (W, H), 0)
        if not 0x7F <= c <= 0x9F:            # DEL and the C1 controls stay blank
            ch = bytes([c]).decode('latin-1')
            x = (W - f.getlength(ch)) / 2
            ImageDraw.Draw(img).text((x, BASELINE), ch, font=f, fill=255, anchor='ls')
        glyphs.append(img)
    return glyphs

def pack(glyphs):
    out = bytearray()
    for img in glyphs:
        px = img.load()
        for y in range(H):
            for b in range(0, W, 4):
                byte = 0
                for k in range(4):
                    byte |= min(3, (px[b + k, y] + 42) // 85) << (2 * k)
                out.append(byte)
    assert len(out) == (LAST - FIRST + 1) * W * H * 2 // 8
    return bytes(out)

def preview(data, path):
    """Decode the array the way libfont does, so the preview shows what the PS3 draws."""
    text = ['HDD/SSD Health  0123456789', 'Raw read error rate  100 100 0',
            'Reallocated sectors  Temperature 38 C', 'abcdefghijklmnopqrstuvwxyz %#&/()']
    img = Image.new('L', (W * max(map(len, text)), H * len(text)), 24)
    for row, line in enumerate(text):
        for col, ch in enumerate(line):
            base = (ord(ch) - FIRST) * W * H * 2 // 8
            for y in range(H):
                for x in range(W):
                    v = (data[base + y * 4 + x // 4] >> (2 * (x % 4))) & 3
                    if v:
                        img.putpixel((col * W + x, row * H + y), v * 85)
    img.save(path)

def write_c(data, path):
    lines = ['/* Generated by art/make_font.py from JetBrains Mono (SIL Open Font License 1.1,',
             ' * github.com/JetBrains/JetBrainsMono): characters 32..255, 16x32, 2 bits per',
             ' * pixel, first pixel in bits 0-1. The license ships as USRDIR/OFL.txt. */',
             f'#define size_font {len(data)}', '', f'unsigned char font[{len(data)}] = {{']
    for i in range(0, len(data), 16):
        lines.append('    ' + ', '.join(f'0x{b:02x}' for b in data[i:i + 16]) + ',')
    lines.append('};')
    open(path, 'w').write('\n'.join(lines) + '\n')

if __name__ == '__main__':
    if len(sys.argv) not in (2, 3):
        sys.exit(__doc__)
    data = pack(render(sys.argv[1]))
    here = os.path.dirname(os.path.abspath(__file__))
    write_c(data, os.path.join(here, '..', 'source', 'font.c'))
    if len(sys.argv) == 3:
        preview(data, sys.argv[2])
    print(f'source/font.c: {len(data)} bytes')
